<?php

/**
 * @file
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run `pnpm generate-config` to regenerate.
 *
 * Bilingual (en/de) field descriptors; the module renders labels in the active
 * interface language. Returned as a plain array required by the module + form.
 */

return [
  'cdnBase' => 'https://widgets.professional-hosting.com/accessibility-widget/v1',
  'assetFiles' => [
    'loader' => 'accessibility-widget-loader.min.js',
    'core' => 'accessibility-widget-core.min.js',
    'css' => 'accessibility-widget.min.css',
  ],
  'groups' => [
    [
      'id' => 'appearance',
      'label' => [
        'en' => 'Appearance',
        'de' => 'Darstellung',
      ],
    ],
    [
      'id' => 'behavior',
      'label' => [
        'en' => 'Behavior',
        'de' => 'Verhalten',
      ],
    ],
    [
      'id' => 'content',
      'label' => [
        'en' => 'Content',
        'de' => 'Inhalt',
      ],
    ],
    [
      'id' => 'features',
      'label' => [
        'en' => 'Features',
        'de' => 'Funktionen',
      ],
    ],
    [
      'id' => 'advanced',
      'label' => [
        'en' => 'Advanced / self-hosting',
        'de' => 'Erweitert / Self-Hosting',
      ],
    ],
  ],
  'fields' => [
    [
      'key' => 'position',
      'group' => 'appearance',
      'type' => 'enum',
      'label' => [
        'en' => 'Position',
        'de' => 'Position',
      ],
      'help' => [
        'en' => 'Where the floating button appears.',
        'de' => 'Wo die Schaltfläche erscheint.',
      ],
      'default' => 'bottom-right',
      'optionsTranslatable' => false,
      'options' => [
        [
          'value' => 'bottom-right',
          'label' => 'bottom-right',
        ],
        [
          'value' => 'bottom-left',
          'label' => 'bottom-left',
        ],
        [
          'value' => 'top-right',
          'label' => 'top-right',
        ],
        [
          'value' => 'top-left',
          'label' => 'top-left',
        ],
      ],
    ],
    [
      'key' => 'offsetX',
      'group' => 'appearance',
      'type' => 'int',
      'label' => [
        'en' => 'Horizontal offset (px)',
        'de' => 'Horizontaler Abstand (px)',
      ],
      'help' => [
        'en' => 'Distance from the screen edge.',
        'de' => 'Abstand zum Bildschirmrand.',
      ],
      'default' => 20,
      'runtimeKey' => 'offset.x',
      'min' => 0,
    ],
    [
      'key' => 'offsetY',
      'group' => 'appearance',
      'type' => 'int',
      'label' => [
        'en' => 'Vertical offset (px)',
        'de' => 'Vertikaler Abstand (px)',
      ],
      'help' => [
        'en' => 'Distance from the screen edge.',
        'de' => 'Abstand zum Bildschirmrand.',
      ],
      'default' => 20,
      'runtimeKey' => 'offset.y',
      'min' => 0,
    ],
    [
      'key' => 'zIndex',
      'group' => 'appearance',
      'type' => 'int',
      'label' => [
        'en' => 'z-index',
        'de' => 'z-index',
      ],
      'help' => [
        'en' => 'Stacking order of the widget. Increase if it sits behind other elements.',
        'de' => 'Stapelreihenfolge des Widgets. Erhöhen, falls es hinter anderen Elementen liegt.',
      ],
      'default' => 2147483646,
      'min' => 0,
    ],
    [
      'key' => 'primaryColor',
      'group' => 'appearance',
      'type' => 'color',
      'label' => [
        'en' => 'Brand color',
        'de' => 'Markenfarbe',
      ],
      'help' => [
        'en' => 'Color of the floating button.',
        'de' => 'Farbe der Schaltfläche.',
      ],
      'default' => '#0058a3',
    ],
    [
      'key' => 'locale',
      'group' => 'appearance',
      'type' => 'enum',
      'label' => [
        'en' => 'Language',
        'de' => 'Sprache',
      ],
      'help' => [
        'en' => 'Widget UI language. "Auto" detects the browser/page language.',
        'de' => 'Sprache der Widget-Oberfläche. „Auto“ erkennt die Browser-/Seitensprache.',
      ],
      'default' => 'auto',
      'optionsTranslatable' => false,
      'options' => [
        [
          'value' => 'auto',
          'label' => 'Auto',
        ],
        [
          'value' => 'de',
          'label' => 'Deutsch',
        ],
        [
          'value' => 'en',
          'label' => 'English',
        ],
        [
          'value' => 'fr',
          'label' => 'Français',
        ],
        [
          'value' => 'es',
          'label' => 'Español',
        ],
        [
          'value' => 'it',
          'label' => 'Italiano',
        ],
        [
          'value' => 'pl',
          'label' => 'Polski',
        ],
        [
          'value' => 'tr',
          'label' => 'Türkçe',
        ],
        [
          'value' => 'ar',
          'label' => 'العربية',
        ],
        [
          'value' => 'zh',
          'label' => '中文',
        ],
        [
          'value' => 'hi',
          'label' => 'हिन्दी',
        ],
        [
          'value' => 'pt',
          'label' => 'Português',
        ],
        [
          'value' => 'bn',
          'label' => 'বাংলা',
        ],
        [
          'value' => 'ru',
          'label' => 'Русский',
        ],
        [
          'value' => 'ja',
          'label' => '日本語',
        ],
        [
          'value' => 'ko',
          'label' => '한국어',
        ],
        [
          'value' => 'vi',
          'label' => 'Tiếng Việt',
        ],
        [
          'value' => 'fa',
          'label' => 'فارسی',
        ],
        [
          'value' => 'ur',
          'label' => 'اردو',
        ],
        [
          'value' => 'th',
          'label' => 'ไทย',
        ],
        [
          'value' => 'id',
          'label' => 'Bahasa Indonesia',
        ],
        [
          'value' => 'he',
          'label' => 'עברית',
        ],
        [
          'value' => 'nl',
          'label' => 'Nederlands',
        ],
        [
          'value' => 'sv',
          'label' => 'Svenska',
        ],
        [
          'value' => 'cs',
          'label' => 'Čeština',
        ],
        [
          'value' => 'el',
          'label' => 'Ελληνικά',
        ],
        [
          'value' => 'hu',
          'label' => 'Magyar',
        ],
        [
          'value' => 'ro',
          'label' => 'Română',
        ],
        [
          'value' => 'uk',
          'label' => 'Українська',
        ],
      ],
    ],
    [
      'key' => 'buttonLabel',
      'group' => 'appearance',
      'type' => 'string',
      'label' => [
        'en' => 'Button label',
        'de' => 'Schaltflächen-Beschriftung',
      ],
      'help' => [
        'en' => 'Accessible label for the button. Empty uses the localized default.',
        'de' => 'Barrierefreie Beschriftung der Schaltfläche. Leer = lokalisierter Standard.',
      ],
      'nullable' => true,
    ],
    [
      'key' => 'draggableFab',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => [
        'en' => 'Draggable button',
        'de' => 'Verschiebbare Schaltfläche',
      ],
      'help' => [
        'en' => 'Let visitors drag the button to reposition it.',
        'de' => 'Besucher können die Schaltfläche verschieben.',
      ],
      'default' => false,
    ],
    [
      'key' => 'respectReducedMotion',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => [
        'en' => 'Respect reduced motion',
        'de' => '„Reduzierte Bewegung“ beachten',
      ],
      'help' => [
        'en' => 'Honor the visitor\'s prefers-reduced-motion setting.',
        'de' => 'Die Einstellung „prefers-reduced-motion“ des Besuchers berücksichtigen.',
      ],
      'default' => true,
    ],
    [
      'key' => 'hideOnPrint',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => [
        'en' => 'Hide on print',
        'de' => 'Beim Drucken ausblenden',
      ],
      'help' => [
        'en' => 'Hide the widget on printed pages.',
        'de' => 'Widget in der Druckansicht ausblenden.',
      ],
      'default' => true,
    ],
    [
      'key' => 'keyboardShortcut',
      'group' => 'behavior',
      'type' => 'string',
      'label' => [
        'en' => 'Keyboard shortcut',
        'de' => 'Tastenkürzel',
      ],
      'help' => [
        'en' => 'Shortcut to open the widget (e.g. ctrl+alt+a). Empty disables it.',
        'de' => 'Tastenkürzel zum Öffnen (z. B. ctrl+alt+a). Leer = deaktiviert.',
      ],
      'default' => 'ctrl+alt+a',
      'special' => 'keyboardShortcut',
    ],
    [
      'key' => 'storageKey',
      'group' => 'behavior',
      'type' => 'string',
      'label' => [
        'en' => 'Storage key',
        'de' => 'Speicher-Schlüssel',
      ],
      'help' => [
        'en' => 'localStorage key for saved visitor preferences. Change only to avoid conflicts.',
        'de' => 'localStorage-Schlüssel für gespeicherte Einstellungen. Nur bei Konflikten ändern.',
      ],
      'default' => 'accessibility-widget',
    ],
    [
      'key' => 'hidePoweredBy',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => [
        'en' => 'Hide "powered by"',
        'de' => '„Powered by“ ausblenden',
      ],
      'help' => [
        'en' => 'Hide the provider credit in the widget panel.',
        'de' => 'Den Anbieter-Hinweis im Widget ausblenden.',
      ],
      'default' => false,
    ],
    [
      'key' => 'debug',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => [
        'en' => 'Debug logging',
        'de' => 'Debug-Protokollierung',
      ],
      'help' => [
        'en' => 'Log diagnostic messages to the browser console.',
        'de' => 'Diagnosemeldungen in der Browser-Konsole ausgeben.',
      ],
      'default' => false,
    ],
    [
      'key' => 'statementUrl',
      'group' => 'content',
      'type' => 'url',
      'label' => [
        'en' => 'Accessibility statement URL',
        'de' => 'URL der Barrierefreiheitserklärung',
      ],
      'help' => [
        'en' => 'Link to your accessibility statement.',
        'de' => 'Link zu Ihrer Barrierefreiheitserklärung.',
      ],
      'validate' => 'url-safe',
      'nullable' => true,
    ],
    [
      'key' => 'disclaimer',
      'group' => 'content',
      'type' => 'string',
      'label' => [
        'en' => 'Disclaimer text',
        'de' => 'Haftungsausschluss-Text',
      ],
      'help' => [
        'en' => 'Short note shown in the widget panel.',
        'de' => 'Kurzer Hinweis im Widget-Panel.',
      ],
      'nullable' => true,
    ],
    [
      'key' => 'feature_fontSize',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'fontSize',
      'label' => [
        'en' => 'Font size',
        'de' => 'Schriftgröße',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_lineHeight',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'lineHeight',
      'label' => [
        'en' => 'Line height',
        'de' => 'Zeilenhöhe',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_letterSpacing',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'letterSpacing',
      'label' => [
        'en' => 'Letter spacing',
        'de' => 'Buchstabenabstand',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_contrast',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'contrast',
      'label' => [
        'en' => 'Contrast',
        'de' => 'Kontrast',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_grayscale',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'grayscale',
      'label' => [
        'en' => 'Grayscale',
        'de' => 'Graustufen',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_invertColors',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'invertColors',
      'label' => [
        'en' => 'Invert colors',
        'de' => 'Farben invertieren',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_dyslexiaFont',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'dyslexiaFont',
      'label' => [
        'en' => 'Dyslexia font',
        'de' => 'Dyslexie-Schrift',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_highlightLinks',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'highlightLinks',
      'label' => [
        'en' => 'Highlight links',
        'de' => 'Links hervorheben',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_pauseAnimations',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'pauseAnimations',
      'label' => [
        'en' => 'Pause animations',
        'de' => 'Animationen pausieren',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_bigCursor',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'bigCursor',
      'label' => [
        'en' => 'Big cursor',
        'de' => 'Großer Mauszeiger',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_focusOutline',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'focusOutline',
      'label' => [
        'en' => 'Focus outline',
        'de' => 'Fokus-Umrandung',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_readingMask',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'readingMask',
      'label' => [
        'en' => 'Reading mask',
        'de' => 'Lesemaske',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_readingGuide',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'readingGuide',
      'label' => [
        'en' => 'Reading guide',
        'de' => 'Leselineal',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_tts',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'tts',
      'label' => [
        'en' => 'Text to speech',
        'de' => 'Vorlesefunktion',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'feature_structureNav',
      'group' => 'features',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'structureNav',
      'label' => [
        'en' => 'Structure navigation',
        'de' => 'Struktur-Navigation',
      ],
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => [
            'en' => 'Default (widget decides)',
            'de' => 'Standard (Widget entscheidet)',
          ],
        ],
        [
          'value' => 'on',
          'label' => [
            'en' => 'On by default',
            'de' => 'Standardmäßig an',
          ],
        ],
        [
          'value' => 'off',
          'label' => [
            'en' => 'Off by default',
            'de' => 'Standardmäßig aus',
          ],
        ],
        [
          'value' => 'disabled',
          'label' => [
            'en' => 'Hidden',
            'de' => 'Ausgeblendet',
          ],
        ],
      ],
    ],
    [
      'key' => 'assetBase',
      'group' => 'advanced',
      'type' => 'url',
      'label' => [
        'en' => 'Asset base URL',
        'de' => 'Asset-Basis-URL',
      ],
      'help' => [
        'en' => 'Empty loads from the BAUER GROUP CDN (recommended, always current). Set only to self-host/mirror.',
        'de' => 'Leer = Laden vom BAUER GROUP CDN (empfohlen, immer aktuell). Nur zum Self-Hosting/Spiegeln setzen.',
      ],
      'asset' => 'base',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'corePath',
      'group' => 'advanced',
      'type' => 'url',
      'label' => [
        'en' => 'Core script URL',
        'de' => 'Core-Skript-URL',
      ],
      'help' => [
        'en' => 'Overrides the derived core bundle URL. Advanced self-hosting only.',
        'de' => 'Überschreibt die abgeleitete Core-Bundle-URL. Nur für fortgeschrittenes Self-Hosting.',
      ],
      'asset' => 'core',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'cssPath',
      'group' => 'advanced',
      'type' => 'url',
      'label' => [
        'en' => 'Stylesheet URL',
        'de' => 'Stylesheet-URL',
      ],
      'help' => [
        'en' => 'Overrides the derived stylesheet URL. Advanced self-hosting only.',
        'de' => 'Überschreibt die abgeleitete Stylesheet-URL. Nur für fortgeschrittenes Self-Hosting.',
      ],
      'asset' => 'css',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'coreIntegrity',
      'group' => 'advanced',
      'type' => 'string',
      'label' => [
        'en' => 'Core SRI hash',
        'de' => 'Core-SRI-Hash',
      ],
      'help' => [
        'en' => 'Subresource Integrity hash for a pinned core URL. Only with a fixed self-hosted version.',
        'de' => 'Subresource-Integrity-Hash für eine gepinnte Core-URL. Nur mit fester, selbst gehosteter Version.',
      ],
      'asset' => 'coreIntegrity',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'cssIntegrity',
      'group' => 'advanced',
      'type' => 'string',
      'label' => [
        'en' => 'Stylesheet SRI hash',
        'de' => 'Stylesheet-SRI-Hash',
      ],
      'help' => [
        'en' => 'Subresource Integrity hash for a pinned stylesheet URL.',
        'de' => 'Subresource-Integrity-Hash für eine gepinnte Stylesheet-URL.',
      ],
      'asset' => 'cssIntegrity',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
  ],
];
