<?php

declare(strict_types=1);

namespace BauerGroup\AccessibilityWidget\Model\Config\Source;

use Magento\Framework\Data\OptionSourceInterface;

/**
 * AUTO-GENERATED by scripts/generate-config.mjs — do not edit.
 */
class FeatureState implements OptionSourceInterface
{
    public function toOptionArray(): array
    {
        return [
            ['value' => 'default', 'label' => __('Default (widget decides)')],
            ['value' => 'on', 'label' => __('On by default')],
            ['value' => 'off', 'label' => __('Off by default')],
            ['value' => 'disabled', 'label' => __('Hidden')],
        ];
    }
}
