<?php

declare(strict_types=1);

namespace BauerGroup\AccessibilityWidget\Model\Config\Source;

use Magento\Framework\Data\OptionSourceInterface;

/**
 * AUTO-GENERATED by scripts/generate-config.mjs — do not edit.
 */
class Locale implements OptionSourceInterface
{
    public function toOptionArray(): array
    {
        return [
            ['value' => 'auto', 'label' => 'Auto'],
            ['value' => 'de', 'label' => 'Deutsch'],
            ['value' => 'en', 'label' => 'English'],
            ['value' => 'fr', 'label' => 'Français'],
            ['value' => 'es', 'label' => 'Español'],
            ['value' => 'it', 'label' => 'Italiano'],
            ['value' => 'pl', 'label' => 'Polski'],
            ['value' => 'tr', 'label' => 'Türkçe'],
            ['value' => 'ar', 'label' => 'العربية'],
            ['value' => 'zh', 'label' => '中文'],
            ['value' => 'hi', 'label' => 'हिन्दी'],
            ['value' => 'pt', 'label' => 'Português'],
            ['value' => 'bn', 'label' => 'বাংলা'],
            ['value' => 'ru', 'label' => 'Русский'],
            ['value' => 'ja', 'label' => '日本語'],
            ['value' => 'ko', 'label' => '한국어'],
            ['value' => 'vi', 'label' => 'Tiếng Việt'],
            ['value' => 'fa', 'label' => 'فارسی'],
            ['value' => 'ur', 'label' => 'اردو'],
            ['value' => 'th', 'label' => 'ไทย'],
            ['value' => 'id', 'label' => 'Bahasa Indonesia'],
            ['value' => 'he', 'label' => 'עברית'],
            ['value' => 'nl', 'label' => 'Nederlands'],
            ['value' => 'sv', 'label' => 'Svenska'],
            ['value' => 'cs', 'label' => 'Čeština'],
            ['value' => 'el', 'label' => 'Ελληνικά'],
            ['value' => 'hu', 'label' => 'Magyar'],
            ['value' => 'ro', 'label' => 'Română'],
            ['value' => 'uk', 'label' => 'Українська'],
        ];
    }
}
