<?php

declare(strict_types=1);

namespace BauerGroup\AccessibilityWidget\Model\Config\Source;

use Magento\Framework\Data\OptionSourceInterface;

/**
 * AUTO-GENERATED by scripts/generate-config.mjs — do not edit.
 */
class Position implements OptionSourceInterface
{
    public function toOptionArray(): array
    {
        return [
            ['value' => 'bottom-right', 'label' => 'bottom-right'],
            ['value' => 'bottom-left', 'label' => 'bottom-left'],
            ['value' => 'top-right', 'label' => 'top-right'],
            ['value' => 'top-left', 'label' => 'top-left'],
        ];
    }
}
