<?php
/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run `pnpm generate-config` to regenerate.
 *
 * English label/help strings are the gettext msgids; German lives in
 * languages/accessibility-widget-de_DE.(po|mo).
 */

if (!defined('ABSPATH')) {
    exit;
}

return [
  'cdnBase' => 'https://widgets.professional-hosting.com/accessibility-widget/v1',
  'assetFiles' => [
    'loader' => 'accessibility-widget-loader.min.js',
    'core' => 'accessibility-widget-core.min.js',
    'css' => 'accessibility-widget.min.css',
  ],
  'groups' => [
    [
      'id' => 'appearance',
      'label' => 'Appearance',
    ],
    [
      'id' => 'behavior',
      'label' => 'Behavior',
    ],
    [
      'id' => 'content',
      'label' => 'Content',
    ],
    [
      'id' => 'features',
      'label' => 'Features',
    ],
    [
      'id' => 'advanced',
      'label' => 'Advanced / self-hosting',
    ],
  ],
  'fields' => [
    [
      'key' => 'position',
      'group' => 'appearance',
      'type' => 'enum',
      'label' => 'Position',
      'help' => 'Where the floating button appears.',
      'default' => 'bottom-right',
      'optionsTranslatable' => false,
      'options' => [
        [
          'value' => 'bottom-right',
          'label' => 'bottom-right',
        ],
        [
          'value' => 'bottom-left',
          'label' => 'bottom-left',
        ],
        [
          'value' => 'top-right',
          'label' => 'top-right',
        ],
        [
          'value' => 'top-left',
          'label' => 'top-left',
        ],
      ],
    ],
    [
      'key' => 'offsetX',
      'group' => 'appearance',
      'type' => 'int',
      'label' => 'Horizontal offset (px)',
      'help' => 'Distance from the screen edge.',
      'default' => 20,
      'runtimeKey' => 'offset.x',
      'min' => 0,
    ],
    [
      'key' => 'offsetY',
      'group' => 'appearance',
      'type' => 'int',
      'label' => 'Vertical offset (px)',
      'help' => 'Distance from the screen edge.',
      'default' => 20,
      'runtimeKey' => 'offset.y',
      'min' => 0,
    ],
    [
      'key' => 'zIndex',
      'group' => 'appearance',
      'type' => 'int',
      'label' => 'z-index',
      'help' => 'Stacking order of the widget. Increase if it sits behind other elements.',
      'default' => 2147483646,
      'min' => 0,
    ],
    [
      'key' => 'primaryColor',
      'group' => 'appearance',
      'type' => 'color',
      'label' => 'Brand color',
      'help' => 'Color of the floating button.',
      'default' => '#0058a3',
    ],
    [
      'key' => 'locale',
      'group' => 'appearance',
      'type' => 'enum',
      'label' => 'Language',
      'help' => 'Widget UI language. "Auto" detects the browser/page language.',
      'default' => 'auto',
      'optionsTranslatable' => false,
      'options' => [
        [
          'value' => 'auto',
          'label' => 'Auto',
        ],
        [
          'value' => 'de',
          'label' => 'Deutsch',
        ],
        [
          'value' => 'en',
          'label' => 'English',
        ],
        [
          'value' => 'fr',
          'label' => 'Français',
        ],
        [
          'value' => 'es',
          'label' => 'Español',
        ],
        [
          'value' => 'it',
          'label' => 'Italiano',
        ],
        [
          'value' => 'pl',
          'label' => 'Polski',
        ],
        [
          'value' => 'tr',
          'label' => 'Türkçe',
        ],
        [
          'value' => 'ar',
          'label' => 'العربية',
        ],
        [
          'value' => 'zh',
          'label' => '中文',
        ],
        [
          'value' => 'hi',
          'label' => 'हिन्दी',
        ],
        [
          'value' => 'pt',
          'label' => 'Português',
        ],
        [
          'value' => 'bn',
          'label' => 'বাংলা',
        ],
        [
          'value' => 'ru',
          'label' => 'Русский',
        ],
        [
          'value' => 'ja',
          'label' => '日本語',
        ],
        [
          'value' => 'ko',
          'label' => '한국어',
        ],
        [
          'value' => 'vi',
          'label' => 'Tiếng Việt',
        ],
        [
          'value' => 'fa',
          'label' => 'فارسی',
        ],
        [
          'value' => 'ur',
          'label' => 'اردو',
        ],
        [
          'value' => 'th',
          'label' => 'ไทย',
        ],
        [
          'value' => 'id',
          'label' => 'Bahasa Indonesia',
        ],
        [
          'value' => 'he',
          'label' => 'עברית',
        ],
        [
          'value' => 'nl',
          'label' => 'Nederlands',
        ],
        [
          'value' => 'sv',
          'label' => 'Svenska',
        ],
        [
          'value' => 'cs',
          'label' => 'Čeština',
        ],
        [
          'value' => 'el',
          'label' => 'Ελληνικά',
        ],
        [
          'value' => 'hu',
          'label' => 'Magyar',
        ],
        [
          'value' => 'ro',
          'label' => 'Română',
        ],
        [
          'value' => 'uk',
          'label' => 'Українська',
        ],
      ],
    ],
    [
      'key' => 'buttonLabel',
      'group' => 'appearance',
      'type' => 'string',
      'label' => 'Button label',
      'help' => 'Accessible label for the button. Empty uses the localized default.',
      'nullable' => true,
    ],
    [
      'key' => 'draggableFab',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => 'Draggable button',
      'help' => 'Let visitors drag the button to reposition it.',
      'default' => false,
    ],
    [
      'key' => 'respectReducedMotion',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => 'Respect reduced motion',
      'help' => 'Honor the visitor\'s prefers-reduced-motion setting.',
      'default' => true,
    ],
    [
      'key' => 'hideOnPrint',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => 'Hide on print',
      'help' => 'Hide the widget on printed pages.',
      'default' => true,
    ],
    [
      'key' => 'keyboardShortcut',
      'group' => 'behavior',
      'type' => 'string',
      'label' => 'Keyboard shortcut',
      'help' => 'Shortcut to open the widget (e.g. ctrl+alt+a). Empty disables it.',
      'default' => 'ctrl+alt+a',
      'special' => 'keyboardShortcut',
    ],
    [
      'key' => 'storageKey',
      'group' => 'behavior',
      'type' => 'string',
      'label' => 'Storage key',
      'help' => 'localStorage key for saved visitor preferences. Change only to avoid conflicts.',
      'default' => 'accessibility-widget',
    ],
    [
      'key' => 'hidePoweredBy',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => 'Hide "powered by"',
      'help' => 'Hide the provider credit in the widget panel.',
      'default' => false,
    ],
    [
      'key' => 'debug',
      'group' => 'behavior',
      'type' => 'bool',
      'label' => 'Debug logging',
      'help' => 'Log diagnostic messages to the browser console.',
      'default' => false,
    ],
    [
      'key' => 'statementUrl',
      'group' => 'content',
      'type' => 'url',
      'label' => 'Accessibility statement URL',
      'help' => 'Link to your accessibility statement.',
      'validate' => 'url-safe',
      'nullable' => true,
    ],
    [
      'key' => 'disclaimer',
      'group' => 'content',
      'type' => 'string',
      'label' => 'Disclaimer text',
      'help' => 'Short note shown in the widget panel.',
      'nullable' => true,
    ],
    [
      'key' => 'feature_fontSize',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Font size',
      'default' => 'default',
      'feature' => 'fontSize',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_lineHeight',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Line height',
      'default' => 'default',
      'feature' => 'lineHeight',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_letterSpacing',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Letter spacing',
      'default' => 'default',
      'feature' => 'letterSpacing',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_contrast',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Contrast',
      'default' => 'default',
      'feature' => 'contrast',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_grayscale',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Grayscale',
      'default' => 'default',
      'feature' => 'grayscale',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_invertColors',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Invert colors',
      'default' => 'default',
      'feature' => 'invertColors',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_dyslexiaFont',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Dyslexia font',
      'default' => 'default',
      'feature' => 'dyslexiaFont',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_highlightLinks',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Highlight links',
      'default' => 'default',
      'feature' => 'highlightLinks',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_pauseAnimations',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Pause animations',
      'default' => 'default',
      'feature' => 'pauseAnimations',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_bigCursor',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Big cursor',
      'default' => 'default',
      'feature' => 'bigCursor',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_focusOutline',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Focus outline',
      'default' => 'default',
      'feature' => 'focusOutline',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_readingMask',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Reading mask',
      'default' => 'default',
      'feature' => 'readingMask',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_readingGuide',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Reading guide',
      'default' => 'default',
      'feature' => 'readingGuide',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_tts',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Text to speech',
      'default' => 'default',
      'feature' => 'tts',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'feature_structureNav',
      'group' => 'features',
      'type' => 'feature_state',
      'label' => 'Structure navigation',
      'default' => 'default',
      'feature' => 'structureNav',
      'optionsTranslatable' => true,
      'options' => [
        [
          'value' => 'default',
          'label' => 'Default (widget decides)',
        ],
        [
          'value' => 'on',
          'label' => 'On by default',
        ],
        [
          'value' => 'off',
          'label' => 'Off by default',
        ],
        [
          'value' => 'disabled',
          'label' => 'Hidden',
        ],
      ],
    ],
    [
      'key' => 'assetBase',
      'group' => 'advanced',
      'type' => 'url',
      'label' => 'Asset base URL',
      'help' => 'Empty loads from the BAUER GROUP CDN (recommended, always current). Set only to self-host/mirror.',
      'asset' => 'base',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'corePath',
      'group' => 'advanced',
      'type' => 'url',
      'label' => 'Core script URL',
      'help' => 'Overrides the derived core bundle URL. Advanced self-hosting only.',
      'asset' => 'core',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'cssPath',
      'group' => 'advanced',
      'type' => 'url',
      'label' => 'Stylesheet URL',
      'help' => 'Overrides the derived stylesheet URL. Advanced self-hosting only.',
      'asset' => 'css',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'coreIntegrity',
      'group' => 'advanced',
      'type' => 'string',
      'label' => 'Core SRI hash',
      'help' => 'Subresource Integrity hash for a pinned core URL. Only with a fixed self-hosted version.',
      'asset' => 'coreIntegrity',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
    [
      'key' => 'cssIntegrity',
      'group' => 'advanced',
      'type' => 'string',
      'label' => 'Stylesheet SRI hash',
      'help' => 'Subresource Integrity hash for a pinned stylesheet URL.',
      'asset' => 'cssIntegrity',
      'nullable' => true,
      'emptyMeansDefault' => true,
    ],
  ],
];
