<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run `pnpm generate-config` to regenerate.
 *
 * Structural descriptor consumed by the StorefrontConfigSubscriber.
 */

return [
  'cdnBase' => 'https://widgets.professional-hosting.com/accessibility-widget/v1',
  'assetFiles' => [
    'loader' => 'accessibility-widget-loader.min.js',
    'core' => 'accessibility-widget-core.min.js',
    'css' => 'accessibility-widget.min.css',
  ],
  'fields' => [
    [
      'key' => 'position',
      'path' => 'AccessibilityWidget.config.position',
      'type' => 'enum',
      'default' => 'bottom-right',
    ],
    [
      'key' => 'offsetX',
      'path' => 'AccessibilityWidget.config.offsetX',
      'type' => 'int',
      'default' => 20,
      'runtimeKey' => 'offset.x',
      'min' => 0,
    ],
    [
      'key' => 'offsetY',
      'path' => 'AccessibilityWidget.config.offsetY',
      'type' => 'int',
      'default' => 20,
      'runtimeKey' => 'offset.y',
      'min' => 0,
    ],
    [
      'key' => 'zIndex',
      'path' => 'AccessibilityWidget.config.zIndex',
      'type' => 'int',
      'default' => 2147483646,
      'min' => 0,
    ],
    [
      'key' => 'primaryColor',
      'path' => 'AccessibilityWidget.config.primaryColor',
      'type' => 'color',
      'default' => '#0058a3',
    ],
    [
      'key' => 'locale',
      'path' => 'AccessibilityWidget.config.locale',
      'type' => 'enum',
      'default' => 'auto',
    ],
    [
      'key' => 'buttonLabel',
      'path' => 'AccessibilityWidget.config.buttonLabel',
      'type' => 'string',
    ],
    [
      'key' => 'draggableFab',
      'path' => 'AccessibilityWidget.config.draggableFab',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'respectReducedMotion',
      'path' => 'AccessibilityWidget.config.respectReducedMotion',
      'type' => 'bool',
      'default' => true,
    ],
    [
      'key' => 'hideOnPrint',
      'path' => 'AccessibilityWidget.config.hideOnPrint',
      'type' => 'bool',
      'default' => true,
    ],
    [
      'key' => 'keyboardShortcut',
      'path' => 'AccessibilityWidget.config.keyboardShortcut',
      'type' => 'string',
      'default' => 'ctrl+alt+a',
      'special' => 'keyboardShortcut',
    ],
    [
      'key' => 'storageKey',
      'path' => 'AccessibilityWidget.config.storageKey',
      'type' => 'string',
      'default' => 'accessibility-widget',
    ],
    [
      'key' => 'hidePoweredBy',
      'path' => 'AccessibilityWidget.config.hidePoweredBy',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'debug',
      'path' => 'AccessibilityWidget.config.debug',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'statementUrl',
      'path' => 'AccessibilityWidget.config.statementUrl',
      'type' => 'url',
      'validate' => 'url-safe',
    ],
    [
      'key' => 'disclaimer',
      'path' => 'AccessibilityWidget.config.disclaimer',
      'type' => 'string',
    ],
    [
      'key' => 'feature_fontSize',
      'path' => 'AccessibilityWidget.config.feature_fontSize',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'fontSize',
    ],
    [
      'key' => 'feature_lineHeight',
      'path' => 'AccessibilityWidget.config.feature_lineHeight',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'lineHeight',
    ],
    [
      'key' => 'feature_letterSpacing',
      'path' => 'AccessibilityWidget.config.feature_letterSpacing',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'letterSpacing',
    ],
    [
      'key' => 'feature_contrast',
      'path' => 'AccessibilityWidget.config.feature_contrast',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'contrast',
    ],
    [
      'key' => 'feature_grayscale',
      'path' => 'AccessibilityWidget.config.feature_grayscale',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'grayscale',
    ],
    [
      'key' => 'feature_invertColors',
      'path' => 'AccessibilityWidget.config.feature_invertColors',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'invertColors',
    ],
    [
      'key' => 'feature_dyslexiaFont',
      'path' => 'AccessibilityWidget.config.feature_dyslexiaFont',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'dyslexiaFont',
    ],
    [
      'key' => 'feature_highlightLinks',
      'path' => 'AccessibilityWidget.config.feature_highlightLinks',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'highlightLinks',
    ],
    [
      'key' => 'feature_pauseAnimations',
      'path' => 'AccessibilityWidget.config.feature_pauseAnimations',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'pauseAnimations',
    ],
    [
      'key' => 'feature_bigCursor',
      'path' => 'AccessibilityWidget.config.feature_bigCursor',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'bigCursor',
    ],
    [
      'key' => 'feature_focusOutline',
      'path' => 'AccessibilityWidget.config.feature_focusOutline',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'focusOutline',
    ],
    [
      'key' => 'feature_readingMask',
      'path' => 'AccessibilityWidget.config.feature_readingMask',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'readingMask',
    ],
    [
      'key' => 'feature_readingGuide',
      'path' => 'AccessibilityWidget.config.feature_readingGuide',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'readingGuide',
    ],
    [
      'key' => 'feature_tts',
      'path' => 'AccessibilityWidget.config.feature_tts',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'tts',
    ],
    [
      'key' => 'feature_structureNav',
      'path' => 'AccessibilityWidget.config.feature_structureNav',
      'type' => 'feature_state',
      'default' => 'default',
      'feature' => 'structureNav',
    ],
    [
      'key' => 'assetBase',
      'path' => 'AccessibilityWidget.config.assetBase',
      'type' => 'url',
      'asset' => 'base',
    ],
    [
      'key' => 'corePath',
      'path' => 'AccessibilityWidget.config.corePath',
      'type' => 'url',
      'asset' => 'core',
    ],
    [
      'key' => 'cssPath',
      'path' => 'AccessibilityWidget.config.cssPath',
      'type' => 'url',
      'asset' => 'css',
    ],
    [
      'key' => 'coreIntegrity',
      'path' => 'AccessibilityWidget.config.coreIntegrity',
      'type' => 'string',
      'asset' => 'coreIntegrity',
    ],
    [
      'key' => 'cssIntegrity',
      'path' => 'AccessibilityWidget.config.cssIntegrity',
      'type' => 'string',
      'asset' => 'cssIntegrity',
    ],
  ],
];
