<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run `pnpm generate-config` to regenerate.
 *
 * Structural descriptor consumed by Classes/Middleware/WidgetConfigMiddleware.
 */

return [
  'cdnBase' => 'https://widgets.professional-hosting.com/accessibility-widget/v1',
  'assetFiles' => [
    'loader' => 'accessibility-widget-loader.min.js',
    'core' => 'accessibility-widget-core.min.js',
    'css' => 'accessibility-widget.min.css',
  ],
  'fields' => [
    [
      'key' => 'position',
      'type' => 'enum',
      'default' => 'bottom-right',
    ],
    [
      'key' => 'offsetX',
      'type' => 'int',
      'default' => 20,
      'runtimeKey' => 'offset.x',
      'min' => 0,
    ],
    [
      'key' => 'offsetY',
      'type' => 'int',
      'default' => 20,
      'runtimeKey' => 'offset.y',
      'min' => 0,
    ],
    [
      'key' => 'zIndex',
      'type' => 'int',
      'default' => 2147483646,
      'min' => 0,
    ],
    [
      'key' => 'primaryColor',
      'type' => 'color',
      'default' => '#0058a3',
    ],
    [
      'key' => 'locale',
      'type' => 'enum',
      'default' => 'auto',
    ],
    [
      'key' => 'buttonLabel',
      'type' => 'string',
    ],
    [
      'key' => 'draggableFab',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'respectReducedMotion',
      'type' => 'bool',
      'default' => true,
    ],
    [
      'key' => 'hideOnPrint',
      'type' => 'bool',
      'default' => true,
    ],
    [
      'key' => 'keyboardShortcut',
      'type' => 'string',
      'default' => 'ctrl+alt+a',
      'special' => 'keyboardShortcut',
    ],
    [
      'key' => 'storageKey',
      'type' => 'string',
      'default' => 'accessibility-widget',
    ],
    [
      'key' => 'hidePoweredBy',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'debug',
      'type' => 'bool',
      'default' => false,
    ],
    [
      'key' => 'statementUrl',
      'type' => 'url',
      'validate' => 'url-safe',
    ],
    [
      'key' => 'disclaimer',
      'type' => 'string',
    ],
    [
      'key' => 'assetBase',
      'type' => 'url',
      'asset' => 'base',
    ],
    [
      'key' => 'corePath',
      'type' => 'url',
      'asset' => 'core',
    ],
    [
      'key' => 'cssPath',
      'type' => 'url',
      'asset' => 'css',
    ],
    [
      'key' => 'coreIntegrity',
      'type' => 'string',
      'asset' => 'coreIntegrity',
    ],
    [
      'key' => 'cssIntegrity',
      'type' => 'string',
      'asset' => 'cssIntegrity',
    ],
    [
      'key' => 'initiallyEnabled',
      'type' => 'features-list',
      'mode' => 'enable',
    ],
    [
      'key' => 'disabledFeatures',
      'type' => 'features-list',
      'mode' => 'disable',
    ],
  ],
];
