// AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
// Do not edit by hand — run `pnpm generate-config` to regenerate.

/**
 * CDN defaults — the floating `v1` (major) tag, kept in sync from the shared
 * schema. These are the per-package defaults; override the wrapper's
 * `*Src`/`cssHref` inputs only to self-host or mirror the assets.
 */
export const CDN_BASE = 'https://widgets.professional-hosting.com/accessibility-widget/v1';
export const DEFAULT_LOADER_SRC = 'https://widgets.professional-hosting.com/accessibility-widget/v1/accessibility-widget-loader.min.js';
export const DEFAULT_CORE_SRC = 'https://widgets.professional-hosting.com/accessibility-widget/v1/accessibility-widget-core.min.js';
export const DEFAULT_CSS_HREF = 'https://widgets.professional-hosting.com/accessibility-widget/v1/accessibility-widget.min.css';

export type WidgetPosition = 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';

export type WidgetLocale =
  | 'auto'
  | 'de'
  | 'en'
  | 'fr'
  | 'es'
  | 'it'
  | 'pl'
  | 'tr'
  | 'ar'
  | 'zh'
  | 'hi'
  | 'pt'
  | 'bn'
  | 'ru'
  | 'ja'
  | 'ko'
  | 'vi'
  | 'fa'
  | 'ur'
  | 'th'
  | 'id'
  | 'he'
  | 'nl'
  | 'sv'
  | 'cs'
  | 'el'
  | 'hu'
  | 'ro'
  | 'uk';

export type FeatureId =
  | 'fontSize'
  | 'lineHeight'
  | 'letterSpacing'
  | 'contrast'
  | 'grayscale'
  | 'invertColors'
  | 'dyslexiaFont'
  | 'highlightLinks'
  | 'pauseAnimations'
  | 'bigCursor'
  | 'focusOutline'
  | 'readingMask'
  | 'readingGuide'
  | 'tts'
  | 'structureNav';

/**
 * Full runtime configuration accepted by `window.AccessibilityWidgetConfig`.
 * Generated from the shared schema; unknown keys pass through unchanged so the
 * wrapper stays forward-compatible with newer widget releases.
 */
export interface WidgetConfig {
  position?: WidgetPosition;
  offset?: { x: number; y: number };
  zIndex?: number;
  primaryColor?: string;
  locale?: WidgetLocale;
  buttonLabel?: string | null;
  draggableFab?: boolean;
  respectReducedMotion?: boolean;
  hideOnPrint?: boolean;
  keyboardShortcut?: string | false;
  storageKey?: string;
  hidePoweredBy?: boolean;
  debug?: boolean;
  statementUrl?: string | null;
  disclaimer?: string | null;
  initialFeatures?: Partial<Record<FeatureId, boolean>>;
  disabledFeatures?: FeatureId[];
  corePath?: string;
  cssPath?: string;
  coreIntegrity?: string | null;
  cssIntegrity?: string | null;
  [key: string]: unknown;
}
