#!/usr/bin/env node
/**
 * Config generator for the integrations monorepo.
 *
 * Reads the single source of truth (`config/widget-config.mjs`) and writes every
 * integration's native settings surface, i18n catalogs and the typed TS config —
 * so all 13 integrations stay in lockstep from one definition.
 *
 *   node scripts/generate-config.mjs            # write all targets
 *   node scripts/generate-config.mjs --check    # CI drift guard; exits 1 on drift
 *
 * Mirrors `scripts/sync-version.mjs`: a single TARGETS table, an idempotent
 * writer, and a --check mode that recomputes every target and diffs against disk.
 * Fully-generated files are written whole; mixed files are patched between
 * `BEGIN GENERATED … END GENERATED` markers (the rest stays hand-written).
 *
 * --check additionally fails if any option/group/feature label or help text is
 * missing its `en` or `de` string — the structural guarantee that the admin UIs
 * never drift back into a mixed-language state.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import * as S from '../config/widget-config.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// ── fs helpers ──────────────────────────────────────────────────────────────
const read = (rel) => readFileSync(join(ROOT, rel), 'utf8');
function write(rel, content) {
  const abs = join(ROOT, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

/** Replace the text between two literal markers (markers themselves preserved). */
function replaceBetween(content, begin, end, inner) {
  const b = content.indexOf(begin);
  if (b === -1) throw new Error(`Begin marker not found: ${begin}`);
  const e = content.indexOf(end, b + begin.length);
  if (e === -1) throw new Error(`End marker not found: ${end}`);
  return content.slice(0, b + begin.length) + inner + content.slice(e);
}

/** Extract the current text between two markers (for --check). */
function extractBetween(content, begin, end) {
  const b = content.indexOf(begin);
  const e = b === -1 ? -1 : content.indexOf(end, b + begin.length);
  if (b === -1 || e === -1) return null;
  return content.slice(b + begin.length, e);
}

// ── schema-derived runtime helpers (shared by emitters) ─────────────────────
/** Scalar options (everything except the synthetic `features` block). */
const SCALARS = S.OPTIONS.filter((o) => o.type !== 'features');
/** The per-feature setting keys, e.g. `feature_fontSize`. */
const featureKey = (id) => `${S.FEATURE_KEY_PREFIX}${id}`;

// ── TypeScript types emitter (shared by all 6 JS wrapper packages) ──────────
function tsTypeAlias(name, values) {
  const inline = values.map((v) => `'${v}'`).join(' | ');
  const oneLine = `export type ${name} = ${inline};`;
  if (oneLine.length <= 100) return oneLine;
  return `export type ${name} =\n${values.map((v) => `  | '${v}'`).join('\n')};`;
}

function tsConfigInterface() {
  const props = [];
  let offsetDone = false;
  for (const o of S.OPTIONS) {
    if (o.asset === 'base') continue; // admin-only; resolves into corePath/cssPath
    if (o.runtimeKey?.startsWith('offset.')) {
      if (!offsetDone) {
        props.push('  offset?: { x: number; y: number };');
        offsetDone = true;
      }
      continue;
    }
    if (o.type === 'features') {
      props.push('  initialFeatures?: Partial<Record<FeatureId, boolean>>;');
      props.push('  disabledFeatures?: FeatureId[];');
      continue;
    }
    let t;
    if (o.type === 'enum') t = o.source === 'positions' ? 'WidgetPosition' : 'WidgetLocale';
    else if (o.type === 'int') t = 'number';
    else if (o.type === 'bool') t = 'boolean';
    else t = 'string';
    if (o.special === 'keyboardShortcut') t = 'string | false';
    const tsNull =
      o.asset === 'coreIntegrity' || o.asset === 'cssIntegrity' || (o.nullable && !o.asset);
    if (tsNull) t = `${t} | null`;
    props.push(`  ${o.key}?: ${t};`);
  }
  props.push('  [key: string]: unknown;');
  return props.join('\n');
}

function emitTsTypes() {
  return `// AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
// Do not edit by hand — run \`pnpm generate-config\` to regenerate.

${tsTypeAlias('WidgetPosition', S.POSITIONS)}

${tsTypeAlias('WidgetLocale', S.LOCALES)}

${tsTypeAlias(
  'FeatureId',
  S.FEATURES.map((f) => f.id),
)}

/**
 * Full runtime configuration accepted by \`window.AccessibilityWidgetConfig\`.
 * Generated from the shared schema; unknown keys pass through unchanged so the
 * wrapper stays forward-compatible with newer widget releases.
 */
export interface WidgetConfig {
${tsConfigInterface()}
}
`;
}

// ── shared i18n (stable key + en + de for every translatable schema string) ─
/**
 * The canonical translatable set. `key` is a stable identifier for keyed-i18n
 * platforms (TYPO3 `LLL:`, Shopify `t:`); `en`/`de` drive gettext-style catalogs
 * (WordPress, Drupal, Magento) which key by the English source string.
 */
function i18nEntries() {
  const out = [];
  for (const g of S.GROUPS) out.push({ key: `group.${g.id}`, en: g.label.en, de: g.label.de });
  for (const o of SCALARS) {
    out.push({ key: `option.${o.key}.label`, en: o.i18n.label.en, de: o.i18n.label.de });
    out.push({ key: `option.${o.key}.help`, en: o.i18n.help.en, de: o.i18n.help.de });
  }
  const featuresBlock = S.OPTIONS.find((o) => o.type === 'features');
  out.push({
    key: 'features.help',
    en: featuresBlock.i18n.help.en,
    de: featuresBlock.i18n.help.de,
  });
  for (const f of S.FEATURES) out.push({ key: `feature.${f.id}`, en: f.label.en, de: f.label.de });
  for (const st of S.FEATURE_STATES) {
    out.push({ key: `featureState.${st.value}`, en: st.label.en, de: st.label.de });
  }
  return out;
}

/** Dedupe a list of {en,de,...} by English source (gettext catalogs key by msgid). */
function dedupeByEn(pairs) {
  const seen = new Set();
  return pairs.filter((p) => (seen.has(p.en) ? false : seen.add(p.en)));
}

// ── PHP value serializer (for generated *.php descriptor files) ─────────────
const phpStr = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
function phpValue(v, indent = '') {
  if (v === true) return 'true';
  if (v === false) return 'false';
  if (v === null) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return phpStr(v);
  const inner = indent + '  ';
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    return `[\n${v.map((x) => inner + phpValue(x, inner)).join(',\n')},\n${indent}]`;
  }
  const entries = Object.entries(v);
  if (entries.length === 0) return '[]';
  return `[\n${entries
    .map(([k, val]) => `${inner}${phpStr(k)} => ${phpValue(val, inner)}`)
    .join(',\n')},\n${indent}]`;
}

// ── flat-field model (one admin setting per scalar option + one per feature) ─
/**
 * Expand the schema into the flat list of admin settings every server platform
 * shares (one tri-state field per feature). Labels/help are carried as `{en,de}`;
 * enum option labels are plain strings (positions raw, locales endonyms) and never
 * translated, while feature-state option labels are `{en,de}`. Per-platform
 * emitters flatten this to whatever their i18n mechanism needs.
 */
function flatFields() {
  const fields = [];
  for (const o of S.OPTIONS) {
    if (o.type === 'features') {
      for (const f of S.FEATURES) {
        fields.push({
          key: featureKey(f.id),
          group: 'features',
          type: 'feature_state',
          default: S.FEATURE_STATE_DEFAULT,
          feature: f.id,
          label: { en: f.label.en, de: f.label.de },
          optionsTranslatable: true,
          options: S.FEATURE_STATES.map((st) => ({
            value: st.value,
            label: { en: st.label.en, de: st.label.de },
          })),
        });
      }
      continue;
    }
    const field = {
      key: o.key,
      group: o.group,
      type: o.type,
      label: { en: o.i18n.label.en, de: o.i18n.label.de },
      help: { en: o.i18n.help.en, de: o.i18n.help.de },
    };
    if (o.default !== undefined) field.default = o.default;
    if (o.runtimeKey) field.runtimeKey = o.runtimeKey;
    if (o.asset) field.asset = o.asset;
    if (o.special) field.special = o.special;
    if (o.validate) field.validate = o.validate;
    if (o.nullable) field.nullable = true;
    if (o.emptyMeansDefault) field.emptyMeansDefault = true;
    if (o.min !== undefined) field.min = o.min;
    if (o.type === 'enum') {
      field.optionsTranslatable = false;
      field.options = S.enumValues(o.source).map((v) => ({
        value: v,
        label: S.enumLabel(o.source, v),
      }));
    }
    fields.push(field);
  }
  return fields;
}

/** Drupal config schema type for a field. */
const drupalType = (f) => (f.type === 'bool' ? 'boolean' : f.type === 'int' ? 'integer' : 'string');

/** YAML scalar (booleans/ints bare, strings single-quoted). */
function yamlScalar(v) {
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

/** Default value a field stores at rest (used by install YAML + descriptors). */
function fieldDefault(f) {
  if (f.default !== undefined) return f.default;
  return f.type === 'bool' ? false : f.type === 'int' ? 0 : '';
}

// ── WordPress emitters ──────────────────────────────────────────────────────
const WP_DIR = 'packages/cms/wordpress/accessibility-widget';

/** Plugin chrome strings (not in the schema) that still need DE+EN. */
const WP_CHROME = [
  {
    en: 'Configure the lazy-loading widget. It loads from the CDN and stays current automatically.',
    de: 'Konfiguration des Lazy-Loading-Widgets. Es wird vom CDN geladen und bleibt automatisch aktuell.',
  },
  { en: 'Documentation', de: 'Dokumentation' },
];

/** Flatten a neutral field to English strings (WordPress translates via gettext). */
function wpField(f) {
  const out = { key: f.key, group: f.group, type: f.type, label: f.label.en };
  if (f.help?.en) out.help = f.help.en;
  if (f.default !== undefined) out.default = f.default;
  if (f.runtimeKey) out.runtimeKey = f.runtimeKey;
  if (f.asset) out.asset = f.asset;
  if (f.special) out.special = f.special;
  if (f.validate) out.validate = f.validate;
  if (f.nullable) out.nullable = true;
  if (f.emptyMeansDefault) out.emptyMeansDefault = true;
  if (f.min !== undefined) out.min = f.min;
  if (f.feature) out.feature = f.feature;
  if (f.options) {
    out.optionsTranslatable = !!f.optionsTranslatable;
    out.options = f.options.map((opt) => ({
      value: opt.value,
      label: typeof opt.label === 'string' ? opt.label : opt.label.en,
    }));
  }
  return out;
}

function emitWpSchema() {
  const data = {
    cdnBase: S.CDN_BASE,
    assetFiles: S.ASSET_FILES,
    groups: S.GROUPS.map((g) => ({ id: g.id, label: g.label.en })),
    fields: flatFields().map(wpField),
  };
  return `<?php
/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run \`pnpm generate-config\` to regenerate.
 *
 * English label/help strings are the gettext msgids; German lives in
 * languages/accessibility-widget-de_DE.(po|mo).
 */

if (!defined('ABSPATH')) {
    exit;
}

return ${phpValue(data)};
`;
}

// gettext .po/.pot/.mo --------------------------------------------------------
const poEscape = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');

function poFile(pairs, lang, translated) {
  const headerFields = [
    'Project-Id-Version: accessibility-widget\\n',
    'MIME-Version: 1.0\\n',
    'Content-Type: text/plain; charset=UTF-8\\n',
    'Content-Transfer-Encoding: 8bit\\n',
    `Language: ${lang}\\n`,
  ];
  const header = `msgid ""\nmsgstr ""\n${headerFields.map((h) => `"${h}"`).join('\n')}\n`;
  const body = pairs
    .map((p) => `msgid "${poEscape(p.en)}"\nmsgstr "${translated ? poEscape(p.de) : ''}"`)
    .join('\n\n');
  return `${header}\n${body}\n`;
}

function wpPoPairs() {
  return dedupeByEn([...i18nEntries(), ...WP_CHROME]);
}

const emitWpPot = () => poFile(wpPoPairs(), '', false);
const emitWpPoDe = () => poFile(wpPoPairs(), 'de_DE', true);

/** Encode a deterministic gettext .mo (sorted by msgid) — what WordPress loads. */
function emitWpMoDe() {
  const headerStr =
    'MIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\n' +
    'Content-Transfer-Encoding: 8bit\nLanguage: de_DE\n';
  const entries = [{ id: '', str: headerStr }];
  for (const p of wpPoPairs()) entries.push({ id: p.en, str: p.de });
  entries.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  const n = entries.length;
  const ids = entries.map((e) => Buffer.from(e.id, 'utf8'));
  const strs = entries.map((e) => Buffer.from(e.str, 'utf8'));
  const oTable = 28;
  const tTable = oTable + n * 8;
  let dataPos = tTable + n * 8;
  const idMeta = [];
  for (const b of ids) {
    idMeta.push([b.length, dataPos]);
    dataPos += b.length + 1;
  }
  const strMeta = [];
  for (const b of strs) {
    strMeta.push([b.length, dataPos]);
    dataPos += b.length + 1;
  }
  const buf = Buffer.alloc(dataPos);
  buf.writeUInt32LE(0x950412de, 0);
  buf.writeUInt32LE(0, 4);
  buf.writeUInt32LE(n, 8);
  buf.writeUInt32LE(oTable, 12);
  buf.writeUInt32LE(tTable, 16);
  buf.writeUInt32LE(0, 20); // hash table size
  buf.writeUInt32LE(dataPos, 24); // hash table offset (unused, size 0)
  for (let i = 0; i < n; i++) {
    buf.writeUInt32LE(idMeta[i][0], oTable + i * 8);
    buf.writeUInt32LE(idMeta[i][1], oTable + i * 8 + 4);
    buf.writeUInt32LE(strMeta[i][0], tTable + i * 8);
    buf.writeUInt32LE(strMeta[i][1], tTable + i * 8 + 4);
  }
  for (let i = 0; i < n; i++) {
    ids[i].copy(buf, idMeta[i][1]);
    strs[i].copy(buf, strMeta[i][1]);
  }
  return buf;
}

// ── Drupal emitters ─────────────────────────────────────────────────────────
const DRUPAL_DIR = 'packages/cms/drupal/accessibility_widget';

/** Field descriptor PHP (bilingual) shared by the module + settings form. */
function emitDrupalFields() {
  const data = {
    cdnBase: S.CDN_BASE,
    assetFiles: S.ASSET_FILES,
    groups: S.GROUPS.map((g) => ({ id: g.id, label: { en: g.label.en, de: g.label.de } })),
    fields: flatFields(),
  };
  return `<?php

/**
 * @file
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run \`pnpm generate-config\` to regenerate.
 *
 * Bilingual (en/de) field descriptors; the module renders labels in the active
 * interface language. Returned as a plain array required by the module + form.
 */

return ${phpValue(data)};
`;
}

function emitDrupalSchemaYml() {
  const lines = [
    'accessibility_widget.settings:',
    '  type: config_object',
    "  label: 'Accessibility Widget settings'",
    '  mapping:',
  ];
  for (const f of flatFields()) {
    lines.push(`    ${f.key}:`);
    lines.push(`      type: ${drupalType(f)}`);
    lines.push(`      label: ${yamlScalar(f.label.en)}`);
  }
  return `${lines.join('\n')}\n`;
}

function emitDrupalInstallYml() {
  return `${flatFields()
    .map((f) => `${f.key}: ${yamlScalar(fieldDefault(f))}`)
    .join('\n')}\n`;
}

// ── Magento emitters ────────────────────────────────────────────────────────
const MAGENTO_DIR = 'packages/shop/magento/BauerGroup_AccessibilityWidget';
const MAGENTO_SRC_NS = 'BauerGroup\\AccessibilityWidget\\Model\\Config\\Source\\';
const xmlEscape = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** A select for enum/feature/bool, a text input otherwise. */
const magentoFieldType = (f) =>
  f.type === 'enum' || f.type === 'feature_state' || f.type === 'bool' ? 'select' : 'text';

function magentoSourceModel(f) {
  if (f.type === 'bool') return 'Magento\\Config\\Model\\Config\\Source\\Yesno';
  if (f.type === 'feature_state') return `${MAGENTO_SRC_NS}FeatureState`;
  if (f.key === 'position') return `${MAGENTO_SRC_NS}Position`;
  if (f.key === 'locale') return `${MAGENTO_SRC_NS}Locale`;
  return null;
}

/** Default for etc/config.xml (booleans as 1/0), or null to omit. */
function magentoDefaultValue(f) {
  if (f.type === 'bool') return fieldDefault(f) ? '1' : '0';
  if (f.type === 'int') return String(fieldDefault(f));
  return f.default !== undefined && f.default !== '' ? String(f.default) : null;
}

/**
 * Lean structural descriptor (no labels) consumed by the PHP injectors. `pathFn`
 * maps a field to its native config path.
 */
function descriptorFields(pathFn) {
  return flatFields().map((f) => {
    const out = { key: f.key, path: pathFn(f), type: f.type };
    if (f.default !== undefined) out.default = f.default;
    if (f.runtimeKey) out.runtimeKey = f.runtimeKey;
    if (f.asset) out.asset = f.asset;
    if (f.special) out.special = f.special;
    if (f.feature) out.feature = f.feature;
    if (f.min !== undefined) out.min = f.min;
    if (f.validate) out.validate = f.validate;
    return out;
  });
}

const magentoFields = () => descriptorFields((f) => `accessibility_widget/${f.group}/${f.key}`);

function emitMagentoSystemXml() {
  const groupsXml = S.GROUPS.map((g, gi) => {
    let sort = 0;
    const fieldsXml = flatFields()
      .filter((f) => f.group === g.id)
      .map((f) => {
        sort += 10;
        const src = magentoSourceModel(f);
        const translate = f.help?.en ? 'label comment' : 'label';
        const lines = [
          `        <field id="${f.key}" translate="${translate}" type="${magentoFieldType(f)}" sortOrder="${sort}" showInDefault="1" showInWebsite="1" showInStore="1">`,
          `          <label>${xmlEscape(f.label.en)}</label>`,
        ];
        if (f.help?.en) lines.push(`          <comment>${xmlEscape(f.help.en)}</comment>`);
        if (src) lines.push(`          <source_model>${src}</source_model>`);
        lines.push('        </field>');
        return lines.join('\n');
      })
      .join('\n');
    return `      <group id="${g.id}" translate="label" type="text" sortOrder="${(gi + 1) * 10}" showInDefault="1" showInWebsite="1" showInStore="1">
        <label>${xmlEscape(g.label.en)}</label>
${fieldsXml}
      </group>`;
  }).join('\n');

  return `<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Config:etc/system_file.xsd">
  <system>
    <section id="accessibility_widget" translate="label" sortOrder="900" showInDefault="1" showInWebsite="1" showInStore="1">
      <class>separator-top</class>
      <label>Accessibility Widget</label>
      <tab>general</tab>
      <resource>BauerGroup_AccessibilityWidget::config</resource>
${groupsXml}
    </section>
  </system>
</config>
`;
}

function emitMagentoConfigXml() {
  const groupsXml = S.GROUPS.map((g) => {
    const fieldsXml = flatFields()
      .filter((f) => f.group === g.id)
      .map((f) => ({ f, v: magentoDefaultValue(f) }))
      .filter((x) => x.v !== null)
      .map((x) => `        <${x.f.key}>${xmlEscape(x.v)}</${x.f.key}>`);
    return fieldsXml.length ? `      <${g.id}>\n${fieldsXml.join('\n')}\n      </${g.id}>` : null;
  })
    .filter(Boolean)
    .join('\n');

  return `<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
  <default>
    <accessibility_widget>
${groupsXml}
    </accessibility_widget>
  </default>
</config>
`;
}

function emitMagentoSchema() {
  const data = { cdnBase: S.CDN_BASE, assetFiles: S.ASSET_FILES, fields: magentoFields() };
  return `<?php

/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run \`pnpm generate-config\` to regenerate.
 *
 * Structural descriptor (no labels) consumed by view/frontend/templates/loader.phtml.
 */

return ${phpValue(data)};
`;
}

function magentoSourceClass(name, options) {
  const items = options
    .map((o) => {
      const label = o.translate ? `__(${phpStr(o.label)})` : phpStr(o.label);
      return `            ['value' => ${phpStr(o.value)}, 'label' => ${label}],`;
    })
    .join('\n');
  return `<?php

declare(strict_types=1);

namespace BauerGroup\\AccessibilityWidget\\Model\\Config\\Source;

use Magento\\Framework\\Data\\OptionSourceInterface;

/**
 * AUTO-GENERATED by scripts/generate-config.mjs — do not edit.
 */
class ${name} implements OptionSourceInterface
{
    public function toOptionArray(): array
    {
        return [
${items}
        ];
    }
}
`;
}

const emitMagentoSourcePosition = () =>
  magentoSourceClass(
    'Position',
    S.POSITIONS.map((v) => ({ value: v, label: v, translate: false })),
  );
const emitMagentoSourceLocale = () =>
  magentoSourceClass(
    'Locale',
    S.LOCALES.map((v) => ({ value: v, label: S.LOCALE_LABELS[v] ?? v, translate: false })),
  );
const emitMagentoSourceFeatureState = () =>
  magentoSourceClass(
    'FeatureState',
    S.FEATURE_STATES.map((st) => ({ value: st.value, label: st.label.en, translate: true })),
  );

const csvRow = (a, b) => `"${a.replace(/"/g, '""')}","${b.replace(/"/g, '""')}"`;
const emitMagentoI18n = (translated) =>
  `${dedupeByEn(i18nEntries())
    .map((p) => csvRow(p.en, translated ? p.de : p.en))
    .join('\n')}\n`;

// ── Shopware emitters ───────────────────────────────────────────────────────
const SHOPWARE_DIR = 'packages/shop/shopware/AccessibilityWidget';

const shopwareFields = () => descriptorFields((f) => `AccessibilityWidget.config.${f.key}`);

const shopwareFieldType = (f) => {
  if (f.type === 'enum' || f.type === 'feature_state') return 'single-select';
  if (f.type === 'bool') return 'bool';
  if (f.type === 'int') return 'int';
  if (f.type === 'color') return 'colorpicker';
  return 'text';
};

/** config.xml defaultValue (booleans as true/false), or null to omit. */
function shopwareDefault(f) {
  if (f.type === 'bool') return fieldDefault(f) ? 'true' : 'false';
  if (f.type === 'int') return String(fieldDefault(f));
  return f.default !== undefined && f.default !== '' ? String(f.default) : null;
}

function shopwareOptionsXml(f) {
  return f.options
    .map((opt) => {
      if (typeof opt.label === 'string') {
        return `        <option><id>${xmlEscape(opt.value)}</id><name>${xmlEscape(opt.label)}</name></option>`;
      }
      return `        <option>
          <id>${xmlEscape(opt.value)}</id>
          <name>${xmlEscape(opt.label.en)}</name>
          <name lang="de-DE">${xmlEscape(opt.label.de)}</name>
        </option>`;
    })
    .join('\n');
}

function emitShopwareConfigXml() {
  const cards = S.GROUPS.map((g) => {
    const fieldsXml = flatFields()
      .filter((f) => f.group === g.id)
      .map((f) => {
        const def = shopwareDefault(f);
        const lines = [
          `    <input-field type="${shopwareFieldType(f)}">`,
          `      <name>${f.key}</name>`,
        ];
        if (def !== null) lines.push(`      <defaultValue>${xmlEscape(def)}</defaultValue>`);
        lines.push(`      <label>${xmlEscape(f.label.en)}</label>`);
        lines.push(`      <label lang="de-DE">${xmlEscape(f.label.de)}</label>`);
        if (f.help?.en) {
          lines.push(`      <helpText>${xmlEscape(f.help.en)}</helpText>`);
          lines.push(`      <helpText lang="de-DE">${xmlEscape(f.help.de)}</helpText>`);
        }
        if (f.options) {
          lines.push('      <options>');
          lines.push(shopwareOptionsXml(f));
          lines.push('      </options>');
        }
        lines.push('    </input-field>');
        return lines.join('\n');
      })
      .join('\n\n');
    return `  <card>
    <title>${xmlEscape(g.label.en)}</title>
    <title lang="de-DE">${xmlEscape(g.label.de)}</title>

${fieldsXml}
  </card>`;
  }).join('\n\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/trunk/src/Core/System/SystemConfig/Schema/config.xsd">
${cards}
</config>
`;
}

function emitShopwareConfigSchema() {
  const data = { cdnBase: S.CDN_BASE, assetFiles: S.ASSET_FILES, fields: shopwareFields() };
  return `<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run \`pnpm generate-config\` to regenerate.
 *
 * Structural descriptor consumed by the StorefrontConfigSubscriber.
 */

return ${phpValue(data)};
`;
}

// ── Shopify emitters ────────────────────────────────────────────────────────
// Online Store 2.0 app blocks cap at 25 interactive + 6 non-interactive settings.
// Full parity is 36, so the 15 per-feature tri-states collapse to two compact
// comma-separated fields (Shopify-only); 21 scalars + 2 = 23 interactive ≤ 25.
const SHOPIFY_DIR = 'packages/shop/shopify';
const SHOPIFY_BEGIN =
  '{%- comment -%} BEGIN GENERATED: accessibility-widget config (scripts/generate-config.mjs) {%- endcomment -%}';
const SHOPIFY_END = '{%- comment -%} END GENERATED {%- endcomment -%}';

const shopifySettingType = (o) =>
  o.type === 'enum'
    ? 'select'
    : o.type === 'int'
      ? 'number'
      : o.type === 'color'
        ? 'color'
        : o.type === 'bool'
          ? 'checkbox'
          : 'text';

function shopifyScalarSetting(o) {
  const s = { type: shopifySettingType(o), id: o.key, label: `t:settings.${o.key}.label` };
  if (o.i18n.help.en) s.info = `t:settings.${o.key}.info`;
  if (o.default !== undefined) s.default = o.default;
  if (o.type === 'int' && o.min !== undefined) s.min = o.min;
  if (o.type === 'enum') {
    s.options = S.enumValues(o.source).map((v) => ({ value: v, label: S.enumLabel(o.source, v) }));
  }
  return s;
}

/** The Shopify schema settings array (headers + scalars + 2 feature fields). */
function shopifySettings() {
  const out = [];
  for (const g of S.GROUPS) {
    out.push({ type: 'header', content: `t:settings.group.${g.id}` });
    if (g.id === 'features') {
      for (const id of ['initiallyEnabled', 'disabledFeatures']) {
        out.push({
          type: 'text',
          id,
          label: `t:settings.${id}.label`,
          info: `t:settings.${id}.info`,
        });
      }
    } else {
      for (const o of SCALARS.filter((s) => s.group === g.id)) out.push(shopifyScalarSetting(o));
    }
  }
  return out;
}

/** The render-tag argument list forwarding every block setting to the snippet. */
function shopifyRenderArgs() {
  const ids = [];
  for (const g of S.GROUPS) {
    if (g.id === 'features') ids.push('initiallyEnabled', 'disabledFeatures');
    else for (const o of SCALARS.filter((s) => s.group === g.id)) ids.push(o.key);
  }
  return ids.map((id) => `  ${id}: block.settings.${id}`).join(',\n');
}

function emitShopifyBlock() {
  const schema = { name: 'Accessibility Widget', target: 'body', settings: shopifySettings() };
  return `{%- comment -%}
  Online Store 2.0 app block. Merchant-configurable via the theme editor.
  AUTO-GENERATED by scripts/generate-config.mjs — do not edit by hand.
{%- endcomment -%}
{% render 'accessibility-widget',
${shopifyRenderArgs()} %}

{% schema %}
${JSON.stringify(schema, null, 2)}
{% endschema %}
`;
}

function emitShopifySnippetRegion() {
  return `
{%- liquid
  assign _cdn = 'https://widgets.professional-hosting.com/accessibility-widget/v1'
  assign _base = assetBase | default: _cdn
  assign _core = corePath | default: ''
  if _core == blank
    assign _core = _base | append: '/accessibility-widget-core.min.js'
  endif
  assign _css = cssPath | default: ''
  if _css == blank
    assign _css = _base | append: '/accessibility-widget.min.css'
  endif
  assign _loader = _base | append: '/accessibility-widget-loader.min.js'
  assign _enabled = initiallyEnabled | default: '' | replace: ' ', '' | split: ','
  assign _disabled = disabledFeatures | default: '' | replace: ' ', '' | split: ','
-%}
<script>
  window.AccessibilityWidgetConfig = {
    corePath: {{ _core | json }},
    cssPath: {{ _css | json }},
    position: {{ position | default: 'bottom-right' | json }},
    offset: { "x": {{ offsetX | default: 20 | json }}, "y": {{ offsetY | default: 20 | json }} },
    zIndex: {{ zIndex | default: 2147483646 | json }},
    primaryColor: {{ primaryColor | default: '#0058a3' | json }},
    locale: {{ locale | default: 'auto' | json }},
    draggableFab: {{ draggableFab | default: false, allow_false: true | json }},
    respectReducedMotion: {{ respectReducedMotion | default: true, allow_false: true | json }},
    hideOnPrint: {{ hideOnPrint | default: true, allow_false: true | json }},
    keyboardShortcut: {% if keyboardShortcut == blank %}false{% else %}{{ keyboardShortcut | json }}{% endif %},
    storageKey: {{ storageKey | default: 'accessibility-widget' | json }},
    hidePoweredBy: {{ hidePoweredBy | default: false, allow_false: true | json }},
    debug: {{ debug | default: false, allow_false: true | json }},
    {%- if buttonLabel != blank %}
    buttonLabel: {{ buttonLabel | json }},
    {%- endif %}
    {%- if statementUrl != blank %}{%- assign _scheme = statementUrl | split: ':' | first | downcase %}{%- unless _scheme == 'javascript' or _scheme == 'data' %}
    statementUrl: {{ statementUrl | json }},
    {%- endunless %}{%- endif %}
    {%- if disclaimer != blank %}
    disclaimer: {{ disclaimer | json }},
    {%- endif %}
    {%- if coreIntegrity != blank %}
    coreIntegrity: {{ coreIntegrity | json }},
    {%- endif %}
    {%- if cssIntegrity != blank %}
    cssIntegrity: {{ cssIntegrity | json }},
    {%- endif %}
    initialFeatures: { {%- for f in _enabled %}{%- if f != blank %}{{ f | json }}: true,{%- endif %}{%- endfor %} },
    disabledFeatures: [ {%- for f in _disabled %}{%- if f != blank %}{{ f | json }},{%- endif %}{%- endfor %} ]
  };
</script>
<script src="{{ _loader | escape }}" defer data-aw-loader="1"></script>
`;
}

function emitShopifyLocale(lang) {
  const settings = { group: {} };
  for (const g of S.GROUPS) settings.group[g.id] = g.label[lang];
  for (const o of SCALARS) {
    settings[o.key] = { label: o.i18n.label[lang] };
    if (o.i18n.help.en) settings[o.key].info = o.i18n.help[lang];
  }
  const ids = S.FEATURES.map((f) => f.id).join(', ');
  const prefixEnabled =
    lang === 'de'
      ? 'Kommagetrennte Funktions-IDs, standardmäßig aktiviert: '
      : 'Comma-separated feature IDs to enable by default: ';
  const prefixDisabled =
    lang === 'de'
      ? 'Kommagetrennte Funktions-IDs, die ausgeblendet werden: '
      : 'Comma-separated feature IDs to hide: ';
  settings.initiallyEnabled = {
    label: lang === 'de' ? 'Standardmäßig aktivierte Funktionen' : 'Initially enabled features',
    info: prefixEnabled + ids,
  };
  settings.disabledFeatures = {
    label: lang === 'de' ? 'Ausgeblendete Funktionen' : 'Hidden features',
    info: prefixDisabled + ids,
  };
  return `${JSON.stringify({ settings }, null, 2)}\n`;
}

// ── TYPO3 emitters ──────────────────────────────────────────────────────────
// Settings live in Extension Configuration (ext_conf_template.txt, auto-rendered
// GUI). Like Shopify, the 15 features collapse to two comma-separated string
// fields. A PSR-15 middleware injects the config securely (replaces the previous
// raw TypoScript interpolation). Field labels are bilingual via LLL/XLIFF.
const TYPO3_DIR = 'packages/cms/typo3/accessibility_widget';
const TYPO3_LLL = 'LLL:EXT:accessibility_widget/Resources/Private/Language/locallang.xlf:';

/** Structural descriptor (compact features) consumed by the middleware. */
function typo3Fields() {
  const fields = SCALARS.map((o) => {
    const out = { key: o.key, type: o.type };
    if (o.default !== undefined) out.default = o.default;
    if (o.runtimeKey) out.runtimeKey = o.runtimeKey;
    if (o.asset) out.asset = o.asset;
    if (o.special) out.special = o.special;
    if (o.min !== undefined) out.min = o.min;
    if (o.validate) out.validate = o.validate;
    return out;
  });
  fields.push({ key: 'initiallyEnabled', type: 'features-list', mode: 'enable' });
  fields.push({ key: 'disabledFeatures', type: 'features-list', mode: 'disable' });
  return fields;
}

const typo3ConfType = (o) => {
  if (o.type === 'enum') {
    const opts = S.enumValues(o.source)
      .map((v) => `${S.enumLabel(o.source, v)}=${v}`)
      .join(',');
    return `options[${opts}]`;
  }
  if (o.type === 'bool') return 'boolean';
  if (o.type === 'int') return 'int+';
  return 'string';
};

const typo3ConfDefault = (o) => {
  if (o.type === 'bool') return fieldDefault(o) ? '1' : '0';
  if (o.type === 'int') return String(fieldDefault(o));
  return o.default !== undefined ? String(o.default) : '';
};

function emitTypo3ConfTemplate() {
  const lines = [];
  for (const g of S.GROUPS) {
    let order = 0;
    if (g.id === 'features') {
      for (const key of ['initiallyEnabled', 'disabledFeatures']) {
        order += 10;
        lines.push(`# cat=${g.id}/a/${order}; type=string; label=${TYPO3_LLL}option.${key}.label`);
        lines.push(`${key} =`);
        lines.push('');
      }
    } else {
      for (const o of SCALARS.filter((s) => s.group === g.id)) {
        order += 10;
        lines.push(
          `# cat=${g.id}/a/${order}; type=${typo3ConfType(o)}; label=${TYPO3_LLL}option.${o.key}.label`,
        );
        lines.push(`${o.key} = ${typo3ConfDefault(o)}`);
        lines.push('');
      }
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitTypo3Schema() {
  const data = { cdnBase: S.CDN_BASE, assetFiles: S.ASSET_FILES, fields: typo3Fields() };
  return `<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs.
 * Do not edit by hand — run \`pnpm generate-config\` to regenerate.
 *
 * Structural descriptor consumed by Classes/Middleware/WidgetConfigMiddleware.
 */

return ${phpValue(data)};
`;
}

function typo3XlfUnits() {
  const units = SCALARS.map((o) => ({
    id: `option.${o.key}.label`,
    en: o.i18n.label.en,
    de: o.i18n.label.de,
  }));
  units.push({
    id: 'option.initiallyEnabled.label',
    en: 'Initially enabled features (comma-separated IDs)',
    de: 'Standardmäßig aktivierte Funktionen (kommagetrennte IDs)',
  });
  units.push({
    id: 'option.disabledFeatures.label',
    en: 'Hidden features (comma-separated IDs)',
    de: 'Ausgeblendete Funktionen (kommagetrennte IDs)',
  });
  return units;
}

function emitTypo3Xlf(lang) {
  const isDe = lang === 'de';
  const body = typo3XlfUnits()
    .map((u) => {
      const target = isDe ? `\n        <target>${xmlEscape(u.de)}</target>` : '';
      return `      <trans-unit id="${xmlEscape(u.id)}" resname="${xmlEscape(u.id)}">
        <source>${xmlEscape(u.en)}</source>${target}
      </trans-unit>`;
    })
    .join('\n');
  const langAttr = isDe ? ' target-language="de"' : '';
  return `<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en"${langAttr} datatype="plaintext" original="EXT:accessibility_widget/Resources/Private/Language/locallang.xlf" product-name="accessibility_widget">
    <body>
${body}
    </body>
  </file>
</xliff>
`;
}

// ── Documentation emitter ───────────────────────────────────────────────────
function emitConfigDocs() {
  const out = [
    '<!-- AUTO-GENERATED by scripts/generate-config.mjs from config/widget-config.mjs. Do not edit. -->',
    '',
    '# Configuration reference',
    '',
    'Every integration exposes the same options of `window.AccessibilityWidgetConfig`,',
    'generated from [`config/widget-config.mjs`](../config/widget-config.mjs). Labels and',
    'help are shipped in **English and German**; each admin UI renders in its own language.',
    '',
    '**Flattened admin settings → runtime shape:**',
    '',
    '- `offsetX` / `offsetY` → `offset: { x, y }`',
    '- per-feature tri-state `feature_<id>` (`default|on|off|disabled`) → `initialFeatures` + `disabledFeatures`',
    '  (Shopify and TYPO3 use two compact comma-separated fields instead, within their platform limits)',
    '- `assetBase` derives `corePath` / `cssPath` unless those are set explicitly (Advanced)',
    '',
  ];
  for (const g of S.GROUPS) {
    out.push(`## ${g.label.en} — ${g.label.de}`, '');
    out.push('| Key | Type | Default | Description (EN) | Beschreibung (DE) |');
    out.push('| --- | --- | --- | --- | --- |');
    if (g.id === 'features') {
      for (const f of S.FEATURES) {
        out.push(
          `| \`feature_${f.id}\` | tri-state | \`default\` | ${f.label.en} | ${f.label.de} |`,
        );
      }
    } else {
      for (const o of SCALARS.filter((s) => s.group === g.id)) {
        const def = o.default !== undefined ? `\`${o.default}\`` : '—';
        out.push(`| \`${o.key}\` | ${o.type} | ${def} | ${o.i18n.help.en} | ${o.i18n.help.de} |`);
      }
    }
    out.push('');
  }
  return `${out.join('\n').trimEnd()}\n`;
}

// ── schema validation (always runs; --check fails on any gap) ───────────────
function validateSchema() {
  const errors = [];
  const bothLangs = (obj, where) => {
    if (!obj || !obj.en || !obj.de) errors.push(`${where}: missing en/de`);
  };
  for (const g of S.GROUPS) bothLangs(g.label, `group ${g.id}`);
  for (const f of S.FEATURES) bothLangs(f.label, `feature ${f.id}`);
  for (const st of S.FEATURE_STATES) bothLangs(st.label, `feature-state ${st.value}`);
  for (const o of S.OPTIONS) {
    bothLangs(o.i18n?.label, `option ${o.key} label`);
    bothLangs(o.i18n?.help, `option ${o.key} help`);
    if (!S.GROUPS.some((g) => g.id === o.group)) errors.push(`option ${o.key}: unknown group`);
  }
  if (errors.length) {
    throw new Error(`Schema validation failed:\n  ${errors.join('\n  ')}`);
  }
}

// ── targets ─────────────────────────────────────────────────────────────────
const JS_PKGS = ['react', 'vue', 'angular', 'svelte', 'nuxt', 'astro'];

/**
 * Each target is either:
 *   { file, mode:'full', content() }                      whole-file generation
 *   { file, mode:'region', begin, end, inner() }          patch between markers
 */
const TARGETS = [
  // JS wrappers — full typed config surface, emitted into each package's src/.
  ...JS_PKGS.map((pkg) => ({
    file: `packages/js/${pkg}/src/widget-config.generated.ts`,
    mode: 'full',
    content: emitTsTypes,
  })),

  // WordPress — generated config descriptor + gettext catalogs (DE+EN).
  { file: `${WP_DIR}/inc/config-schema.php`, mode: 'full', content: emitWpSchema },
  { file: `${WP_DIR}/languages/accessibility-widget.pot`, mode: 'full', content: emitWpPot },
  { file: `${WP_DIR}/languages/accessibility-widget-de_DE.po`, mode: 'full', content: emitWpPoDe },
  {
    file: `${WP_DIR}/languages/accessibility-widget-de_DE.mo`,
    mode: 'full',
    binary: true,
    content: emitWpMoDe,
  },

  // Drupal — bilingual field descriptors + config schema/install (camelCase keys).
  {
    file: `${DRUPAL_DIR}/accessibility_widget.fields.php`,
    mode: 'full',
    content: emitDrupalFields,
  },
  {
    file: `${DRUPAL_DIR}/config/schema/accessibility_widget.schema.yml`,
    mode: 'full',
    content: emitDrupalSchemaYml,
  },
  {
    file: `${DRUPAL_DIR}/config/install/accessibility_widget.settings.yml`,
    mode: 'full',
    content: emitDrupalInstallYml,
  },

  // Magento — typed admin (source models) + config defaults + i18n CSVs + descriptor.
  { file: `${MAGENTO_DIR}/etc/adminhtml/system.xml`, mode: 'full', content: emitMagentoSystemXml },
  { file: `${MAGENTO_DIR}/etc/config.xml`, mode: 'full', content: emitMagentoConfigXml },
  { file: `${MAGENTO_DIR}/config-schema.php`, mode: 'full', content: emitMagentoSchema },
  {
    file: `${MAGENTO_DIR}/Model/Config/Source/Position.php`,
    mode: 'full',
    content: emitMagentoSourcePosition,
  },
  {
    file: `${MAGENTO_DIR}/Model/Config/Source/Locale.php`,
    mode: 'full',
    content: emitMagentoSourceLocale,
  },
  {
    file: `${MAGENTO_DIR}/Model/Config/Source/FeatureState.php`,
    mode: 'full',
    content: emitMagentoSourceFeatureState,
  },
  { file: `${MAGENTO_DIR}/i18n/en_US.csv`, mode: 'full', content: () => emitMagentoI18n(false) },
  { file: `${MAGENTO_DIR}/i18n/de_DE.csv`, mode: 'full', content: () => emitMagentoI18n(true) },

  // Shopware — full config.xml (native bilingual labels) + structural descriptor.
  {
    file: `${SHOPWARE_DIR}/src/Resources/config/config.xml`,
    mode: 'full',
    content: emitShopwareConfigXml,
  },
  {
    file: `${SHOPWARE_DIR}/src/Resources/config/config-schema.php`,
    mode: 'full',
    content: emitShopwareConfigSchema,
  },

  // Shopify — full app block + region-patched snippet body + locale catalogs.
  {
    file: `${SHOPIFY_DIR}/blocks/accessibility-widget.liquid`,
    mode: 'full',
    content: emitShopifyBlock,
  },
  {
    file: `${SHOPIFY_DIR}/snippets/accessibility-widget.liquid`,
    mode: 'region',
    begin: SHOPIFY_BEGIN,
    end: SHOPIFY_END,
    inner: emitShopifySnippetRegion,
  },
  {
    file: `${SHOPIFY_DIR}/locales/en.default.schema.json`,
    mode: 'full',
    content: () => emitShopifyLocale('en'),
  },
  {
    file: `${SHOPIFY_DIR}/locales/de.schema.json`,
    mode: 'full',
    content: () => emitShopifyLocale('de'),
  },

  // TYPO3 — Extension Configuration template + descriptor + XLIFF (en + de).
  { file: `${TYPO3_DIR}/ext_conf_template.txt`, mode: 'full', content: emitTypo3ConfTemplate },
  { file: `${TYPO3_DIR}/Configuration/config-schema.php`, mode: 'full', content: emitTypo3Schema },
  {
    file: `${TYPO3_DIR}/Resources/Private/Language/locallang.xlf`,
    mode: 'full',
    content: () => emitTypo3Xlf('en'),
  },
  {
    file: `${TYPO3_DIR}/Resources/Private/Language/de.locallang.xlf`,
    mode: 'full',
    content: () => emitTypo3Xlf('de'),
  },

  // Documentation — generated option reference (bilingual table).
  { file: 'docs/configuration.md', mode: 'full', content: emitConfigDocs },
];

// ── apply / check / CLI ─────────────────────────────────────────────────────
function applyConfig() {
  validateSchema();
  const touched = [];
  for (const t of TARGETS) {
    if (t.mode === 'full') {
      write(t.file, t.content());
    } else {
      const current = read(t.file);
      write(t.file, replaceBetween(current, t.begin, t.end, t.inner()));
    }
    touched.push(t.file);
  }
  return touched;
}

function check() {
  validateSchema();
  const drift = [];
  for (const t of TARGETS) {
    if (!existsSync(join(ROOT, t.file))) {
      drift.push(`${t.file}: missing`);
      continue;
    }
    if (t.mode === 'full') {
      if (t.binary) {
        if (!readFileSync(join(ROOT, t.file)).equals(t.content())) {
          drift.push(`${t.file}: out of date`);
        }
      } else if (read(t.file) !== t.content()) {
        drift.push(`${t.file}: out of date`);
      }
    } else {
      const region = extractBetween(read(t.file), t.begin, t.end);
      if (region === null) drift.push(`${t.file}: markers not found`);
      else if (region !== t.inner()) drift.push(`${t.file}: generated region out of date`);
    }
  }
  if (drift.length) {
    console.error('Config drift — regenerate with `pnpm generate-config`:');
    for (const d of drift) console.error(`  ${d}`);
    process.exit(1);
  }
  console.log(`All ${TARGETS.length} generated targets up to date ✓`);
}

const arg = process.argv[2];
if (arg === '--check') {
  check();
} else if (!arg) {
  const touched = applyConfig();
  console.log(`Generated ${touched.length} files from config/widget-config.mjs:`);
  for (const f of touched) console.log(`  ${f}`);
} else {
  console.error('Usage: node scripts/generate-config.mjs [--check]');
  process.exit(1);
}
